export const TENHOU_YAKU_NAMES: Record<string, string> = {
  'Tanyao': '断幺九',
  'Yakuhai': '役牌',
  'Menzen Tsumo': '門前清自摸和',
  'Pinfu': '平和',
  'Iipeiko': '一盃口',
  'Chiitoitsu': '七対子',
  'Toitoi': '対々和',
  'Sanankou': '三暗刻',
  'Sanshoku Doujun': '三色同順',
  'San Doukou': '三色同刻',
  'Ittsu': '一気通貫',
  'Chanta': '混全帯幺九',
  'Junchan': '純全帯幺九',
  'Honitsu': '混一色',
  'Chinitsu': '清一色',
  'Riichi': '立直',
  'Double Riichi': '両立直',
  'Ippatsu': '一発',
  'Rinshan Kaihou': '嶺上開花',
  'Chankan': '槍槓',
  'Haitei': '海底摸月',
  'Houtei': '河底撈魚',
  'Ura Dora': '裏ドラ',
  'Kokushi Musou': '国士無双',
  'San Kantsu': '三槓子',
  'Su Kantsu': '四槓子',
  'Daisangen': '大三元',
  'Shousangen': '小三元',
  'Suu Ankou': '四暗刻',
  'Daisuushii': '大四喜',
  'Shousuushii': '小四喜',
  'Tsuuiisou': '字一色',
  'Chinroutou': '清老頭',
  'Ryuuiisou': '緑一色',
  'Chuuren Poutou': '九蓮宝燈',
  'Tenhou': '天和',
  'Chiihou': '地和',
  'Renhou': '人和',
};

export function toTenhouName(name: string): string {
  return TENHOU_YAKU_NAMES[name] ?? name;
}
